version: '3.9'
services:
  minio:
    image: 'quay.io/minio/minio'
    container_name: minio1
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - 'D:\fanfics:\data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9090"
    networks:
      - localnet
    restart: unless-stopped
  
networks:
  localnet:
    driver: bridge
    name: localnet